name: User Input Example

on:
  workflow_dispatch:
    inputs:
      user_input:
        description: 'User Input'
        required: true

jobs:
  user_input:
    runs-on: ubuntu-latest
    steps:
      - name: Display User Input
        run: |
          echo "User Input: ${{ github.event.inputs.user_input }}"
